/* Additional record code for System generated by the OpenModelica Compiler OpenModelica 1.17.0~dev.beta3-2-g248842f. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "System_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define KPar__desc_added 1
const char* KPar__desc__fields[8] = {"Dose","b","d","kmax","kmin","kabs","BW","f"};
struct record_description KPar__desc = {
  "KPar", /* package_record__X */
  "KPar", /* package.record_X */
  KPar__desc__fields
};

void KPar_construct_p(threadData_t *threadData, void* v_ths ) {
  KPar* ths = (KPar*)(v_ths);
  ths->_Dose = 105.0;
  ths->_b = 0.7328;
  ths->_d = 0.1014;
  ths->_kmax = 0.0426;
  ths->_kmin = 0.0076;
  ths->_kabs = 0.0542;
  ths->_BW = 96.0;
  ths->_f = 0.9;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
KPar omc_KPar(threadData_t *threadData , modelica_real  in_Dose, modelica_real  in_b, modelica_real  in_d, modelica_real  in_kmax, modelica_real  in_kmin, modelica_real  in_kabs, modelica_real  in_BW, modelica_real  in_f) {
  KPar dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in KPar_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  KPar_construct(threadData, dst);
  dst._Dose =  in_Dose;
  dst._b =  in_b;
  dst._d =  in_d;
  dst._kmax =  in_kmax;
  dst._kmin =  in_kmin;
  dst._kabs =  in_kabs;
  dst._BW =  in_BW;
  dst._f =  in_f;
  return dst;
}
*/

void KPar_copy_p(void* v_src, void* v_dst) {
  KPar* src = (KPar*)(v_src);
  KPar* dst = (KPar*)(v_dst);
  dst->_Dose = src->_Dose;
  dst->_b = src->_b;
  dst->_d = src->_d;
  dst->_kmax = src->_kmax;
  dst->_kmin = src->_kmin;
  dst->_kabs = src->_kabs;
  dst->_BW = src->_BW;
  dst->_f = src->_f;
}

#ifdef __cplusplus
}
#endif

